#!/bin/bash
if [ "$1" == "" ];then
    echo "Usage: $0 iptales_num(0, 250*250]"
    exit -1
fi

# arg1=start, arg2=end, format: %s.%N  
function getTiming() {
    start=$1
    end=$2

    start_s=$(echo $start | cut -d '.' -f 1)
    start_ns=$(echo $start | cut -d '.' -f 2)
    end_s=$(echo $end | cut -d '.' -f 1)
    end_ns=$(echo $end | cut -d '.' -f 2)


# for debug..  
#    echo $start  
#    echo $end  


    time=$(( ( 10#$end_s - 10#$start_s ) * 1000 + ( 10#$end_ns / 1000000 - 10#$start_ns / 1000000 ) ))


   # echo "$time ms"  
   echo "$time"  
}

function test_time(){

cmd='iptables -F;'
count=0
ip_base='10.10.'
if [ $1 -gt 250 ];then 
   jj=$(($1/250))
   left=$(($1%250))
   for j in `seq $jj`
   do
       for i in `seq 250`
       do
           ip=$ip_base"$j.$i/32"
#           count=$(($count +1))
           cmd=$cmd"iptables -w -I INPUT -i nic0 -p ip --src $ip -j ACCEPT;"
       done
   done 
   for i in `seq $left`
   do 
       ip=$ip_base"$(($j+1)).$i/32"
       #count=$(($count +1))
       cmd=$cmd"iptables -w -I INPUT -i nic0 -p ip --src $ip -j ACCEPT;"
   
   done
else
    for i in `seq $1`
    do
        num=i
        ip=$ip_base"1.""$i/32"
#     echo  $ip
#    tc qdisc change dev eth0 root netem delay $i'ms'
        cmd=$cmd"iptables -w -I INPUT -i nic0 -p ip --src $ip -j ACCEPT;"
      #     count=$(($count +1))
    done
fi
start=`date +%s.%N`
ip netns exec ns1 eval "$cmd"
end=`date +%s.%N`
getTiming $start $end
}

for i in `seq 10 10 10000`
do
#test_time $i
test_time 10
sleep 1
done 


