#!/bin/bash
# arg1=start, arg2=end, format: %s.%N  
function getTiming() {
    start=$1
    end=$2

    start_s=$(echo $start | cut -d '.' -f 1)
    start_ns=$(echo $start | cut -d '.' -f 2)
    end_s=$(echo $end | cut -d '.' -f 1)
    end_ns=$(echo $end | cut -d '.' -f 2)


# for debug..  
#    echo $start  
#    echo $end  


    time=$(( ( 10#$end_s - 10#$start_s ) * 1000 + ( 10#$end_ns / 1000000 - 10#$start_ns / 1000000 ) ))


    echo "$time"  
}

function test_time(){
    end=$((1+$1))
    cmd='tc qdisc delete dev nic0 root;'
    cmd=$cmd'tc qdisc add dev nic0 root handle 1: htb default 30;'
    cmd=$cmd'tc class add dev nic0 parent 1: classid 1:1 htb rate 1000mbps ceil 1000mbps;'
    for i in `seq 2 1 $end`
    do
    cmd=$cmd'tc class add dev nic0 parent 1:1 classid '"1:$i"' htb rate 10kbps ceil 10kbps;'
    cmd=$cmd'tc filter add dev nic0 parent 1: protocol ip prio 1 u32 match ip dst '"192.168.99.1/32"' flowid '"1:$i;"
    cmd=$cmd'tc qdisc add dev nic0 parent '"1:$i"' netem delay '"$i""ms;"
    done
    #tc filter add dev nic0 parent 1: protocol ip prio 1 handle 1001 fw classid 1:10
    #tc filter add dev nic0 parent 1: protocol ip prio 1 handle 1002 fw classid 1:20
    start=`date +%s.%N`
    ip netns exec ns1 eval "$cmd"
#   echo $cmd
    end=`date +%s.%N`
    
    
    #iptables -t mangle -A POSTROUTING  -d 192.168.99.66/32 -o nic0 -j MARK --set-xmark 1001
    #iptables -t mangle -A POSTROUTING  -d 192.168.99.126/32 -o nic0 -j MARK --set-xmark 1002
    
    getTiming $start $end
}
for i in `seq 10 10 10000`
do
test_time 10
sleep 1
done
