#!/bin/bash
if [ "$1" == "" -o "$2" == "" ];then
    echo "Usage: $0 <tc_num> <call_num>"
    exit -1
fi


./bwlimiter_oneeth $1 $2| awk -F"-" '{if($1 != "#" ){sum=sum+$1;}else if($1 == "#" && $2 !=0){print sum/$2;sum=0;}}'
