#!/bin/bash
BRO="/usr/local/bro/bin/bro"

function usage(){
    echo "Usage:$0 <cpu_index_list> <pcap_dir>"
    echo -e "\tFor example: $0 \"0 2 3\" /home/"
}

if [ "$1" == "" -o ! -d "$2" ];then 
    if [ ! -d "$2" ];then
        echo "ERROR:\"$2\" does not exits!"
    fi
    usage
    exit 1
fi


cpu_arr=($1)

#achieve pcap_dir absolute path
cd "$2"
pcap_dir=`pwd`
pcap_dir="$pcap_dir""/"
cd -

#drop blank element
for i in `seq 0 $((${#cpu_arr[@]} - 1))`
do
    if [ "${cpu_arr[$i]}" == "" ];then 
        unset ${cpu_arr[$i]}
    fi
done
#echo ${#cpu_arr[@]}

#cpu_index is not larger than cpu max
cpu_index_max=`cat /proc/stat | grep cpu|grep grep -v|grep color -v |wc -l`
cpu_index_max=$(($cpu_index_max -2))
#echo $cpu_index_max
for i in `seq 0 $((${#cpu_arr[@]} - 1))`
do
    if [ ${cpu_arr[$i]} -gt $cpu_index_max  ];then
        echo "ERROR: ${cpu_arr[$i]} is larger than max cpu index ($cpu_index_max)!"
        usage
        exit 2
    fi
done

#mkdir log dir
log_path="./log/"
if [ ! -d "$log_path" ];then
    mkdir -p "$log_path"
fi

while [ 1 ]
do
    #wait and achieve pcap file array
    while [ 1 ]
    do
       pcap_list=`ls -tr "$pcap_dir" | grep "\.pcap" |grep color -v | grep grep -v`
       pcap_arr=($pcap_list)
       if [ ${#pcap_arr[@]} -gt 1 ];then
           break
       fi
       echo -en  "\r\r\r\r\r\r\r\r\r\r\r\r\r\r\rWaiting for new pcap files!"
       sleep 2
    done

    #dispatch command to each CPU 
    cnt=0
    for index in `echo ${cpu_arr[*]}`
    do
        #the lastest pcap file can not be  broanylized
        if [ $cnt -ge $((${#pcap_arr[@]} - 1)) ];then
            break
        fi
         
        #remkdir  tmp for every cpu
        tmp="$log_path"".tmp"$index
        if [ ! -d "$tmp" ];then 
            mkdir -p "$tmp"
        else
            rm -rf "$tmp"
            mkdir -p "$tmp"
        fi

        cd $tmp
        cmd="$BRO -C -r $pcap_dir${pcap_arr[$cnt]} &"
        eval "$cmd"
        pid=`ps axu | grep "${pcap_arr[$cnt]}"| grep grep -v| grep color -v|awk -F" " '{print $2}'`
        taskset -pc $index $pid
        cd -
        cnt=$(($cnt +1)) 
    done

    #wait for end of this circle
    cnt=$(($cnt -1))
    while [ 1 ]
    do
        running_cnt=0
        for i in `seq 0 $cnt`
        do
            pid=`ps axu | grep "${pcap_arr[$cnt]}"| grep grep -v| grep color -v|awk -F" " '{print $2}'`
            if [ "$pid" != "" ];then
                running_cnt=$(($running_cnt + 1))
            fi
        done
      
        if [ $running_cnt -eq 0 ];then
            break
        fi
        sleep 0.2
    done
    
    #wait to finish writing data to disk
    sleep 0.8

    #move "log/tmp" log files to "log"
    echo $cnt
    for i in `seq 0 $cnt`
    do
        
        #remove anylized pcap file,release the storage 
        sudo rm -rf "$pcap_dir${pcap_arr[$i]}"

        tmp="$log_path"".tmp""${cpu_arr[$i]}""/"
        name=`basename "${pcap_arr[$i]}" ".pcap"`
        echo $tmp
        ls -tr $tmp
        for p in `ls -tr $tmp`
        do
            #echo "$tmp$p"
            cp "$tmp$p" "$log_path"$p".$name"
        done
    done
    
done
